// ============================================================================
// Kraftt Digital — central site configuration
// This is the single file to edit for agency-wide facts: domain, contact
// details, social profiles, default currency behaviour, and the legal
// business identity used in structured data. Nothing below is invented —
// items not supplied in the source brand/pricing files are placeholders,
// clearly marked, and listed in README.md under "Content Required".
// ============================================================================

export const siteConfig = {
  name: 'Kraftt Digital',
  legalName: 'Kraftt Digital', // CONTENT REQUIRED: confirm registered legal entity name if different
  tagline: 'Digital presence for brands that take themselves seriously.',
  domain: 'https://krafttdigital.in',
  defaultLocale: 'en',
  indiaLocale: 'en-IN',

  description:
    'Kraftt Digital builds websites, Shopify stores, brand identities, content, dashboards and growth marketing for businesses in India and worldwide — transparent INR/USD pricing, fast delivery.',

  logo: {
    wordmark: 'Kraftt',
    subLabel: 'Digital',
    monogram: 'K.',
  },

  assets: {
    socialImage: '/og-image.png',
  },

  contact: {
    email: 'krafttdigital@gmail.com',
    formEndpoint: 'https://formspree.io/f/mzdlrzrq',
    whatsapp: '7986769102',
    phone: '7986769102',
  },

  social: {
    instagram: 'https://www.instagram.com/krafttdigital/',
    linkedin: 'https://www.linkedin.com/company/krafttdigital/',
    twitter: null as string | null, // CONTENT REQUIRED
  },

  areaServed: ['India', 'United States', 'United Kingdom', 'United Arab Emirates', 'Canada', 'Australia'],
  languages: ['English'],

  // ---------------------------------------------------------------------
  // Currency configuration
  // ---------------------------------------------------------------------
  // Every package price in this project was supplied with an explicit
  // INR amount AND an explicit USD amount in the source pricing file —
  // so the live USD figures below are NOT generated by a conversion
  // formula. They are the agency's own deliberately-set international
  // prices (commercially rounded, e.g. $299, $599 — never $247.36).
  //
  // FALLBACK_USD_PER_INR exists only for any *future* SKU added without
  // an explicit USD price. It is a stable, manually-set commercial rate —
  // NOT a live exchange rate — and should be reviewed periodically by
  // the agency, not fetched automatically. To update it, change the
  // single number below; nothing else in the codebase needs to change.
  currency: {
    default: 'USD' as const,
    fallbackUsdPerInr: 1 / 83, // i.e. ~₹83 = $1. Update here only.
    storageKey: 'kraftt-currency',
  },

  // Analytics / verification.
  analytics: {
    gtmContainerId: 'GTM-T44Z78PQ',
    gaStreamName: 'Kraftt Digital',
    gaStreamUrl: 'https://krafttdigital.in',
    gaStreamId: '15164387564',
    gaMeasurementId: 'G-5MLNQBXJY3',
    searchConsoleVerification: '', // CONTENT REQUIRED
  },
};

export type SiteConfig = typeof siteConfig;
